apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-secrets-web-demo
  namespace: vault-live-secrets-demo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
