kind: VaultAuth
apiVersion: secrets.hashicorp.com/v1beta1
metadata:
  name: vaultauth-vault-live-secrets-demo
  namespace: vault-live-secrets-demo
spec:
  vaultConnectionRef: vaultconnection-gcve
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-live-secrets-demo
    serviceAccount: vault-auth
    audiences:
      - https://kubernetes.default.svc
