apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-web-secrets
  namespace: vault-live-secrets-demo
spec:
  vaultAuthRef: vaultauth-vault-live-secrets-demo
  mount: secrets
  type: kv-v2
  path: dev
  destination:
    name: vault-web-secrets
    create: true
  refreshAfter: 3s
