apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared-tfc-eda
spec:
  vaultAuthRef: vaultauth-cloudflared-tfc-eda
  mount: secrets
  type: kv-v2
  path: cloudflared/tfc-eda-tunnel
  destination:
    name: cloudflared-tunnel
    create: true
  refreshAfter: 60s
