apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  api:
  hostname: aap
  bundle_cacert_secret: aap-certificate
  database:
      postgres_storage_class: ocs-storagecluster-cephfs
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    ## Modify to contain your RWM storage class name
    storage_type: file
    file_storage_storage_class: ocs-storagecluster-cephfs
    file_storage_size: 50Gi
  lightspeed:
    disabled: true