apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: gitlabtls
  namespace: gitlab
spec:
  destination:
    create: true
    overwrite: true
    name: gitlab-tls
    type: kubernetes.io/tls
  role: gcve
  mount: pki
  commonName: gitlab.hashicorp.local
  format: pem_bundle
  vaultAuthRef: vaultauth-gitlab