apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: gitlab-scc
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostNetwork: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
allowedCapabilities:
- SETUID
- SETGID
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 1000
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:gitlab:gitlab-sa
