---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gitlab-route
  namespace: gitlab
spec:
  host: gitlab.hashicorp.local
  to:
    kind: Service
    name: gitlab-ce
  port:
    targetPort: https
  tls:
    termination: passthrough