apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: gitlab-scc
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostNetwork: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowedCapabilities:
- SETUID
- SETGID
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:gitlab:gitlab-sa
