---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-ce
  namespace: gitlab
  labels:
    app: gitlab-ce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-ce
  template:
    metadata:
      labels:
        app: gitlab-ce
    spec:
      containers:
      - name: gitlab-ce
        image: gitlab/gitlab-ce:latest
        ports:
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        volumeMounts:
        - name: gitlab-config
          mountPath: /etc/gitlab
        - name: gitlab-logs
          mountPath: /var/log/gitlab
        - name: gitlab-data
          mountPath: /var/opt/gitlab
        - name: ssl-certs
          mountPath: /etc/gitlab/ssl
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 4
            memory: 8Gi
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          value: |
            external_url 'https://gitlab.hashicorp.local'
            nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.example.com.crt"
            nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.example.com.key"
            nginx['redirect_http_to_https'] = true
            gitlab_rails['initial_root_password'] = 'Hashicorp123!'
            gitlab_rails['backup_keep_time'] = 604800
      volumes:
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config-pvc
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-logs-pvc
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data-pvc
      - name: ssl-certs
        secret:
          secretName: gitlab-tls
          defaultMode: 0644