apiVersion: app.terraform.io/v1alpha2
kind: AgentPool
metadata:
  name: agentpooltest
  namespace: tfe
spec:
  organization: gcve
  token:
    secretKeyRef:
      name: hcp-terraform-operator
      key: token
  name: agentpooltest
  agentTokens:
    - name: white
    - name: blue
    - name: red
    - name: yellow
    - name: green
  agentDeployment:
    replicas: 0
    spec:
      containers:
        - name: tfc-agent
          image: "srlynch1/tfc-agent:latest"
          resources:
            requests:
              memory: "1024Mi"
  autoscaling:
    minReplicas: 2
    maxReplicas: 20
    cooldownPeriodSeconds: 60