# Grafana Helm Values for OpenShift
# Generated by Terraform
# Reference: https://github.com/grafana/helm-charts/tree/main/charts/grafana
#
# OpenShift Notes:
# - Uses nonroot-v2 SCC
# - Persistent storage via OpenShift storage class
# - Service type ClusterIP (exposed via OpenShift Route)

# Admin credentials
adminUser: admin
adminPassword: "${admin_password}"

# Replica count
replicas: 1

# Security context for OpenShift
securityContext:
  runAsNonRoot: true
  runAsUser: null
  fsGroup: null

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Resource requests and limits
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

# Persistent storage
persistence:
  enabled: true
  storageClassName: "${storage_class}"
  size: 10Gi
  accessModes:
    - ReadWriteOnce

# Service configuration - use ClusterIP with OpenShift Route
service:
  type: ClusterIP
  port: 80

# Ingress disabled - using OpenShift Route
ingress:
  enabled: false

# Grafana configuration
grafana.ini:
  server:
    root_url: "${root_url}"
    serve_from_sub_path: false

  # Security settings
  security:
    admin_user: admin
    admin_password: "${admin_password}"
    disable_initial_admin_creation: false
    cookie_secure: true
    strict_transport_security: true

  # Authentication
  auth:
    disable_login_form: false

  auth.anonymous:
    enabled: false

  # Users
  users:
    allow_sign_up: false
    allow_org_create: false
    auto_assign_org: true
    auto_assign_org_role: Viewer

  # Logging
  log:
    mode: console
    level: info

  # Feature toggles
  feature_toggles:
    enable: ""

# Datasources configuration
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      # Prometheus datasource
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: "${prometheus_url}"
        access: proxy
        isDefault: true
        editable: true
        jsonData:
          httpMethod: POST
          timeInterval: "30s"

      # Loki datasource for logs
      - name: Loki
        type: loki
        uid: loki
        url: "${loki_url}"
        access: proxy
        isDefault: false
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields:
            # Link traces to logs if using tracing
            - datasourceUid: prometheus
              matcherRegex: "trace_id=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"

# Dashboard providers - load dashboards from configmaps
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

# Pre-installed dashboards from Grafana.com
dashboards:
  default:
    # Kubernetes cluster monitoring
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus

    # Node exporter dashboard
    node-exporter:
      gnetId: 1860
      revision: 37
      datasource: Prometheus

    # Kubernetes pods dashboard
    kubernetes-pods:
      gnetId: 6781
      revision: 1
      datasource: Prometheus

    # Prometheus stats
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus

    # Loki logs dashboard
    loki-logs:
      gnetId: 13639
      revision: 2
      datasource: Loki

    # Loki & Prometheus integration
    loki-promtail:
      gnetId: 10880
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
        - name: DS_LOKI
          value: Loki

# Sidecar for loading dashboards from ConfigMaps
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    folder: /var/lib/grafana/dashboards/default
    provider:
      allowUiUpdates: true
      foldersFromFilesStructure: false

  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "1"

# Plugins to install
plugins:
  - grafana-piechart-panel
  - grafana-clock-panel

# Init containers for plugin installation
initChownData:
  enabled: false

# Image renderer for dashboard snapshots (optional, uses resources)
imageRenderer:
  enabled: false

# SMTP configuration for alerting (disabled by default)
smtp:
  enabled: false

# Test framework
testFramework:
  enabled: false

# Service account
serviceAccount:
  create: true
  name: grafana

# RBAC for reading configmaps/secrets for dashboards
rbac:
  create: true
  pspEnabled: false
  namespaced: true
