# Langfuse Helm Values for OpenShift
# Generated by Terraform
# Reference: https://langfuse.com/self-hosting/deployment/kubernetes-helm

global:
  defaultStorageClass: "${storage_class}"
  # Use Bitnami legacy images due to registry changes
  # See: https://github.com/bitnami/charts/issues/35164
  security:
    allowInsecureImages: true

langfuse:
  nextauth:
    url: "https://${hostname}"
    secret:
      secretKeyRef:
        name: langfuse-secrets
        key: NEXTAUTH_SECRET

  salt:
    secretKeyRef:
      name: langfuse-secrets
      key: SALT

  encryptionKey:
    secretKeyRef:
      name: langfuse-secrets
      key: LANGFUSE_ENCRYPTION_KEY

  # Resource sizing
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"

  # OpenShift ingress disabled - we use Route instead
  ingress:
    enabled: false

  # Service configuration
  service:
    type: ClusterIP
    port: 3000

  # Web pod configuration
  web:
    replicaCount: 1

  # Worker pod configuration  
  worker:
    replicaCount: 1

# Use bundled PostgreSQL
postgresql:
  deploy: true
  auth:
    username: langfuse
    database: langfuse
    password: "${postgres_password}"
  primary:
    persistence:
      storageClass: "${storage_class}"
      size: 50Gi
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"

# Use bundled ClickHouse for analytics
clickhouse:
  deploy: true
  auth:
    username: default
    password: "${clickhouse_password}"
  persistence:
    storageClass: "${storage_class}"
    size: 20Gi
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
  zookeeper:
    persistence:
      storageClass: "${storage_class}"
      size: 5Gi
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"

# Use bundled Redis for caching
redis:
  deploy: true
  architecture: standalone
  auth:
    enabled: true
    password: "${redis_password}"
  primary:
    persistence:
      storageClass: "${storage_class}"
      size: 5Gi
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"

# Use external S3 (Ceph RGW from OpenShift Data Foundation)
s3:
  deploy: false
  bucket: "${s3_bucket}"
  region: "us-east-1"
  endpoint: "${s3_endpoint}"
  forcePathStyle: true
  accessKeyId:
    value: "${s3_access_key}"
  secretAccessKey:
    secretKeyRef:
      name: langfuse
      key: AWS_SECRET_ACCESS_KEY
  eventUpload:
    prefix: "events/"
  batchExport:
    prefix: "exports/"
  mediaUpload:
    prefix: "media/"
