# Loki Helm Values for OpenShift
# Generated by Terraform
# Reference: https://github.com/grafana/loki/tree/main/production/helm/loki
#
# OpenShift Notes:
# - Uses nonroot-v2 SCC
# - SimpleScalable deployment mode for production-like setup
# - Bundled MinIO for S3-compatible object storage
# - Optimized for moderate log volumes

# Deployment mode - SimpleScalable is good for production
deploymentMode: SimpleScalable

# Loki configuration
loki:
  # Authentication disabled for internal cluster use
  auth_enabled: false

  # Common configuration
  commonConfig:
    replication_factor: 1

  # OTLP configuration for receiving logs via OpenTelemetry protocol
  # This enables the /otlp endpoint for OTEL collector to push logs
  distributor:
    otlp_config:
      default_resource_attributes_as_index_labels:
        - service.name
        - tool_name
        - event_name
        - success
        - error

  # Schema configuration
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  # Ingester configuration for log ingestion
  ingester:
    chunk_encoding: snappy

  # Query frontend tuning
  frontend:
    max_outstanding_per_tenant: 2048

  # Limits configuration - tuned for moderate to high volume
  limits_config:
    ingestion_rate_mb: 20
    ingestion_burst_size_mb: 40
    per_stream_rate_limit: 5MB
    per_stream_rate_limit_burst: 15MB
    max_line_size: 256kb
    max_entries_limit_per_query: 10000
    max_query_parallelism: 32
    split_queries_by_interval: 1h
    reject_old_samples: true
    reject_old_samples_max_age: 168h  # 7 days
    # Allow OTLP structured metadata - stores attributes alongside logs
    allow_structured_metadata: true

  # Query range tuning
  query_range:
    align_queries_with_step: true
    cache_results: true

  # Storage configuration - uses bundled MinIO
  storage:
    type: s3
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    s3:
      endpoint: loki-minio.monitoring.svc.cluster.local:9000
      region: us-east-1
      secretAccessKey: supersecret
      accessKeyId: enterprise-logs
      s3ForcePathStyle: true
      insecure: true

# Write path (receives and processes logs)
write:
  replicas: 2

  persistence:
    enabled: true
    storageClass: "${storage_class}"
    size: 10Gi

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  # OpenShift security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: null
    fsGroup: null

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

# Read path (handles queries)
read:
  replicas: 2

  persistence:
    enabled: true
    storageClass: "${storage_class}"
    size: 10Gi

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: null
    fsGroup: null

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

# Backend (compactor, ruler, etc.)
backend:
  replicas: 1

  persistence:
    enabled: true
    storageClass: "${storage_class}"
    size: 10Gi

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: null
    fsGroup: null

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

# Gateway (nginx reverse proxy)
gateway:
  enabled: true
  replicas: 1

  service:
    type: ClusterIP
    port: 80

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

  # Ingress disabled - using OpenShift Route
  ingress:
    enabled: false

  # OpenShift uses different DNS resolver than standard k8s
  nginxConfig:
    resolver: "dns-default.openshift-dns.svc.cluster.local."

# Bundled MinIO for S3-compatible storage
minio:
  enabled: true

  replicas: 1

  persistence:
    enabled: true
    storageClass: "${storage_class}"
    size: 50Gi

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  # MinIO root credentials
  rootUser: enterprise-logs
  rootPassword: supersecret

  # OpenShift compatibility
  securityContext:
    runAsNonRoot: true
    runAsUser: null
    fsGroup: null

  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true

  # CRITICAL: Disable MinIO's SCC creation - it creates a malformed SCC
  # that breaks pod scheduling. We use existing nonroot-v2 SCC instead.
  securityContextConstraints:
    enabled: false

# Result caching
resultsCache:
  enabled: true
  allocatedMemory: 256

# Chunks caching
chunksCache:
  enabled: true
  allocatedMemory: 512

# Disable single binary mode (using SimpleScalable)
singleBinary:
  replicas: 0

# Canary for testing log ingestion
lokiCanary:
  enabled: false

# Test framework
test:
  enabled: false

# Monitoring - Prometheus metrics
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus

# RBAC
rbac:
  create: true
  pspEnabled: false

# Service account
serviceAccount:
  create: true
  name: loki
