# Prometheus Helm Values for OpenShift
# Generated by Terraform
# Reference: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
#
# OpenShift Notes:
# - Uses nonroot-v2 SCC for server, alertmanager, kube-state-metrics
# - Uses hostaccess SCC for node-exporter (requires host filesystem/network)
# - Persistent storage via OpenShift storage class
# - Service type ClusterIP (exposed via OpenShift Route)

# Server configuration
server:
  enabled: true

  # Run as non-root user for OpenShift compatibility
  securityContext:
    runAsNonRoot: true
    runAsUser: null
    fsGroup: null

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  # Persistent storage
  persistentVolume:
    enabled: true
    storageClass: "${storage_class}"
    size: 50Gi

  # Resource requests
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  # Retention settings
  retention: "15d"

  # Service configuration - use ClusterIP with OpenShift Route
  service:
    type: ClusterIP
    servicePort: 80

  # Ingress disabled - using OpenShift Route
  ingress:
    enabled: false

# Alertmanager configuration
alertmanager:
  enabled: true

  securityContext:
    runAsNonRoot: true
    runAsUser: null
    fsGroup: null

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  persistentVolume:
    enabled: true
    storageClass: "${storage_class}"
    size: 5Gi

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# Kube-state-metrics for Kubernetes object metrics
kube-state-metrics:
  enabled: true

  securityContext:
    runAsNonRoot: true
    runAsUser: null
    fsGroup: null

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# Node exporter for host-level metrics
prometheus-node-exporter:
  enabled: true

  # Node exporter needs host access for system metrics
  # Uses hostaccess SCC in OpenShift
  hostNetwork: true
  hostPID: true
  hostRootFsMount:
    enabled: true
    mountPropagation: HostToContainer

  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

  # Tolerations to run on all nodes including control plane
  tolerations:
    - effect: NoSchedule
      operator: Exists

# Pushgateway - disabled by default (enable if needed for batch jobs)
prometheus-pushgateway:
  enabled: false

# ConfigMap reload sidecar
configmapReload:
  prometheus:
    enabled: true
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        cpu: "50m"
        memory: "64Mi"

# Additional scrape configs can be added here
# Example: Vault metrics endpoint
# extraScrapeConfigs: |
#   - job_name: 'vault'
#     metrics_path: '/v1/sys/metrics'
#     params:
#       format: ['prometheus']
#     scheme: https
#     tls_config:
#       insecure_skip_verify: true
#     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#     static_configs:
#       - targets: ['vault.vault.svc.cluster.local:8200']

# Server global configuration
serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 30s
      evaluation_interval: 30s

    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml

    scrape_configs:
      # Prometheus self-monitoring
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090

      # Kubernetes API server
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

      # Kubernetes nodes
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      # Kubernetes pods with prometheus.io annotations
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
            action: replace
            regex: (https?)
            target_label: __scheme__
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

      # Kubernetes services with prometheus.io annotations
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name
