# Sentry Helm Values for OpenShift
# Generated by Terraform
# Reference: https://github.com/sentry-kubernetes/charts
#
# Resource sizing notes:
# - Sentry minimum: 4 CPU, 16GB RAM total
# - These values target ~24GB RAM, ~12 CPU for comfortable headroom
# - ClickHouse is the heaviest component (analytics DB)
# - Workers are memory-hungry (Python/Celery)

# System configuration
system:
  url: "https://${hostname}"
  secretKey: "${secret_key}"

# Admin user configuration
user:
  create: true
  email: "${admin_email}"
  password: "${admin_password}"

# Main Sentry service configuration
sentry:
  web:
    replicas: 2
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"

  worker:
    replicas: 2
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"

  cron:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

  ingestConsumer:
    replicas: 2
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"

  # Additional consumers for metrics and replays
  ingestMetricsConsumerPerf:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

  ingestReplayRecordings:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

  ingestMonitors:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"

  postProcessForwardErrors:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

  postProcessForwardTransactions:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

# NGINX configuration (reverse proxy)
nginx:
  replicas: 2
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"

# Disable Helm chart ingress - using OpenShift Route instead
ingress:
  enabled: false

# Snuba configuration (analytics query layer for ClickHouse)
snuba:
  api:
    replicas: 2
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"

  consumer:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

  outcomesConsumer:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

  replacer:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

  subscriptionConsumerEvents:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

  subscriptionConsumerTransactions:
    replicas: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

# Relay configuration (Rust-based event relay/filtering)
relay:
  replicas: 2
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"

# Symbolicator configuration (stack trace processing - CPU intensive)
symbolicator:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"

# Vroom configuration (profiling service)
vroom:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"

# External PostgreSQL (via Crunchy Postgres Operator)
postgresql:
  enabled: false

externalPostgresql:
  host: "${postgres_host}"
  port: ${postgres_port}
  username: "${postgres_username}"
  password: "${postgres_password}"
  database: "${postgres_database}"
  sslMode: "require"

# Bundled Redis configuration (caching and rate limiting)
redis:
  enabled: true
  auth:
    enabled: true
    password: "${redis_password}"
  master:
    persistence:
      storageClass: "${storage_class}"
      size: 10Gi
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
  replica:
    replicaCount: 0

# Bundled Kafka configuration (KRaft mode - message broker)
kafka:
  enabled: true
  kraft:
    enabled: true
  controller:
    replicaCount: 1
    persistence:
      storageClass: "${storage_class}"
      size: 30Gi
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
    heapOpts: "-Xmx1536m -Xms1536m"
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT

# Bundled ClickHouse configuration (analytics database - heaviest component)
clickhouse:
  enabled: true
  clickhouse:
    replicas: 1
    persistence:
      storageClass: "${storage_class}"
      size: 100Gi
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"

# Zookeeper for ClickHouse coordination
zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    storageClass: "${storage_class}"
    size: 10Gi
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
  heapSize: 768

# S3 Storage configuration (Ceph RGW from OpenShift Data Foundation)
filestore:
  backend: "s3"
  s3:
    bucketName: "${s3_bucket}"
    endpointUrl: "${s3_endpoint}"
    region: "us-east-1"
    accessKey: "${s3_access_key}"
    secretKey: "${s3_secret_key}"

# Additional S3 configuration for nodestore
config:
  sentryConfPy: |
    # S3 configuration for blob storage
    import sentry_sdk

    SENTRY_OPTIONS["filestore.backend"] = "s3"
    SENTRY_OPTIONS["filestore.options"] = {
        "bucket_name": "${s3_bucket}",
        "endpoint_url": "${s3_endpoint}",
        "access_key": "${s3_access_key}",
        "secret_key": "${s3_secret_key}",
    }
%{ if mail_host != "" }
    # Mail configuration
    SENTRY_OPTIONS["mail.backend"] = "smtp"
    SENTRY_OPTIONS["mail.host"] = "${mail_host}"
    SENTRY_OPTIONS["mail.port"] = ${mail_port}
    SENTRY_OPTIONS["mail.username"] = "${mail_username}"
    SENTRY_OPTIONS["mail.password"] = "${mail_password}"
    SENTRY_OPTIONS["mail.use-tls"] = True
    SENTRY_OPTIONS["mail.from"] = "sentry@${hostname}"
%{ endif }

# Hooks for database migrations
hooks:
  enabled: true
  removeOnSuccess: true
  dbCheck:
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
  dbInit:
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"

# Service account configuration
serviceAccount:
  create: true
  annotations: {}

# Pod security context for OpenShift compatibility
securityContext:
  fsGroup: null
  runAsUser: null
  runAsGroup: null

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
