apiVersion: apps.gitlab.com/v1beta2
kind: Runner
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
spec:
  gitlabUrl: "https://gitlab.com"
  buildImage: "alpine"
  tags: "openshift"
  runners:
    privileged: true
  serviceAccountName: "gitlab-runner"  # Use a service account if needed

  env:
    - name: RUNNER_TOKEN
      valueFrom:
        secretKeyRef:
          name: gitlab-runner-secret
          key: runner-token
